- name: default
  type: postgres
  host: localhost
  database: dataportal
  synchronize: false
  migrationsRun: true
  logging: false
  entities:
  - src/entity/**/*.ts
  migrations:
  - src/migration/**/*.ts
  subscribers:
  - src/subscriber/**/*.ts
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber
- name: test
  type: postgres
  host: localhost
  database: dataportal-test
  synchronize: true
  logging: false
  entities:
  - src/entity/**/*.ts
  migrations:
  - src/migration/**/*.ts
  subscribers:
  - src/subscriber/**/*.ts
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber
- name: ci-test
  type: postgres
  host: localhost
  database: dataportal-test
  synchronize: true
  logging: false
  entities:
    - build/entity/**/*.js
  migrations:
    - build/migration/**/*.js
  subscribers:
    - build/subscriber/**/*.js
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber
- name: docker
  type: postgres
  host: dataportal-db
  username: dataportal
  password: dev
  database: dataportal
  synchronize: false
  logging: "error"
  entities:
    - build/entity/**/*.ts
  migrations:
    - build/migration/**/*.ts
  subscribers:
    - build/subscriber/**/*.ts
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber
