- name: default
  type: postgres
  host: localhost
  database: dataportal
  synchronize: true
  logging: false
  entities:
  - build/entity/**/*.js
  migrations:
  - build/migration/**/*.js
  subscribers:
  - build/subscriber/**/*.js
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber
- name: test
  type: postgres
  host: localhost
  database: dataportal-test
  synchronize: true
  logging: false
  entities:
  - build/entity/**/*.js
  migrations:
  - build/migration/**/*.js
  subscribers:
  - build/subscriber/**/*.js
  cli:
    entitiesDir: src/entity
    migrationsDir: src/migration
    subscribersDir: src/subscriber

