<style scoped lang="sass">
@import "../sass/variables.sass"
@import "../sass/global.sass"

.infobox
  margin-top: 0.5em
  padding: 1em
.infocolor
  background: $landing-header
  font-size: 0.9em
  > h4:first-child
    margin-top: 0
  h4
    font-size: 1.1em
    margin-top: 1em
</style>


<template>
  <!-- eslint-disable max-len -->
  <section id="howtocite">
    This is an example of how to cite Cloudnet datasets. You may freely edit the text to suit publication standards.
    <div class="infobox infocolor">
      <h4>Data availability</h4>
      <div class="citationtext">The ground-based remote-sensing data used in this article are generated by the European Research Infrastructure for the observation of Aerosol, Clouds and Trace Gases (ACTRIS) and are available from the ACTRIS Data Centre using the following link: <a :href="pid">{{ pid }}</a>.</div>
      <h4>Acknowledgements</h4>
      <div class="citationtext">We acknowledge ACTRIS for providing the {{ datasetCreator }} dataset in this study, which was produced by the Finnish Meteorological Institute, and is available for download from <a href="https://cloudnet.fmi.fi/">https://cloudnet.fmi.fi/</a>.</div>
      <!--
[optional for ACTRIS sites .i.e. for discussion]
foreach SITE in SITES
The cloud radar, ceilometer and microwave radiometer data for [SITE] was provided by [PROVIDER]. [PROVIDER TEXT]
Additional text for Cloudnet data from ARM/NOAA/other sites:
* ARM *
The cloud radar, ceilometer and microwave radiometer data for the ARM site[s] used in this study ([SITES]) were obtained from the Atmospheric Radiation Measurement (ARM) user facility, managed by the Office of Biological and Environmental Research for the U.S. Department of Energy Office of Science.
* NOAA (Summit station, could be others in the future) *
The cloud radar, ceilometer and microwave radiometer data for the Summit Station were obtained from NOAA; overall programmatic and logistical support for was provided by the US National Science Foundation, with additional instrumental support provided by the NOAA Earth System Research Laboratories, the DOE Atmospheric Radiation Measurement Program, and Environment Canada.
* Other (European, campaign) stations *
The cloud radar, ceilometer and microwave radiometer data for [SITES] was provided by [PROVIDER]. [PROVIDER TEXT]
-->
      <h4>Citation</h4>
      <div class="citationtext">{{ datasetCreator }}: cloud profiling product{{ products.length > 1 ? 's' : ''}} {{ products.join(', ')}}; {{ startDate + (endDate ? ` - ${endDate}` : '') }}; {{ sites.join(', ')}}. Generated by the cloud profiling unit of the ACTRIS Data Centre, <a :href="pid">{{ pid }}</a>, {{ year }}.</div>
    </div>
  </section>
</template>


<script lang="ts">
import {Component, Prop} from 'vue-property-decorator'
import Vue from 'vue'

@Component
export default class HowToCite extends Vue {
  @Prop() pid!: string
  @Prop() products!: string[]
  @Prop() sites!: string[]
  @Prop() startDate!: string
  @Prop() endDate!: string | null
  @Prop() collectionYear!: string | null

  get year() {
    if (this.collectionYear) return this.collectionYear
    return new Date(this.startDate).getFullYear()
  }

  get datasetCreator() {
    return `CLU (${this.collectionYear})`
  }

}
</script>
