#!/bin/sh
set -e
if [ "$#" -ne 2 ]; then
  echo "USAGE: $0 username upload-site"
  exit 1
fi
(curl --silent -X POST http://localhost:3000/user-accounts -H "Content-Type: application/json" --data-binary @- | jq -r '"https://cloudnet.fmi.fi/credentials/" + .activationToken') << EOF
{
  "username": "$1",
  "permissions": [
    {
      "siteId": "$2",
      "permission": "canUpload"
    }
  ]
}
EOF
