import {MigrationInterface, QueryRunner} from "typeorm";

export class ChangeUuidToAutogeneratedId1603185826535 implements MigrationInterface {
    name = 'ChangeUuidToAutogeneratedId1603185826535'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "model_file" RENAME COLUMN "uuid" TO "id"`);
        await queryRunner.query(`ALTER TABLE "model_file" RENAME CONSTRAINT "PK_fc253af1bf074f42da1c667ac6b" TO "PK_fc23a103c4a50db21fa83fc16ad"`);
        await queryRunner.query(`ALTER TABLE "model_file" DROP CONSTRAINT "PK_fc23a103c4a50db21fa83fc16ad"`);
        await queryRunner.query(`ALTER TABLE "model_file" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "model_file" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_file" ADD CONSTRAINT "PK_fc23a103c4a50db21fa83fc16ad" PRIMARY KEY ("id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "model_file" DROP CONSTRAINT "PK_fc23a103c4a50db21fa83fc16ad"`);
        await queryRunner.query(`ALTER TABLE "model_file" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "model_file" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "model_file" ADD CONSTRAINT "PK_fc23a103c4a50db21fa83fc16ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "model_file" RENAME CONSTRAINT "PK_fc23a103c4a50db21fa83fc16ad" TO "PK_fc253af1bf074f42da1c667ac6b"`);
        await queryRunner.query(`ALTER TABLE "model_file" RENAME COLUMN "id" TO "uuid"`);
    }

}
