#!/bin/sh
set -e

if [ "$1" != "major" ] && [ "$1" != "minor" ] && [ "$1" != "patch" ]; then
  echo "Usage: $0 [major|minor|patch]"
  exit 1
fi

main_branch=$(git rev-parse --abbrev-ref origin/HEAD | cut -c8-)
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "$main_branch" ]; then
  echo "Error: not in '$main_branch' branch"
  exit 1
fi

cd backend
version=$(npm version --no-git-tag-version "$1")
git add package*

cd ../frontend
npm version --no-git-tag-version "$version" > /dev/null
git add package*

git commit -m "Release $version"
git tag -am "$version" "$version"
git push
git push --tags
