<style scoped lang="sass">
@import "../../sass/landing-beta.sass"
</style>

<template>
  <div class="summary-section" id="citation">
    <section class="citation-section" id="citation">
      <div class="citation-header-container">
        <div class="summary-section-header">Citation</div>
        <div class="citation-export">
          <a href="#">Bibtex</a>
          <a href="#">EndNote</a>
          <a href="#">Refman</a>
          <a href="#">RefWorks</a>
        </div>
      </div>
      <!--div class="citation-section-content">
        CLU (2019): Cloud profiling product: Classification; 2019-04-01; from Norunda. Generated by the cloud profiling
        unit of the ACTRIS Data Centre, <a href="">https://hdl.handle.net/21.12132/1.cef4264f6fb24459</a>, 2019.
      </div-->
      <div class="citation-section-content" :class="{ small: smallCitation }" @dblclick="toggleCitation">
        {{ citationString }}<span v-if="smallCitation"> &#183; &#183; &#183;</span>
      </div>
    </section>
    <section class="citation-section">
      <div class="summary-section-header">Acknowledgements</div>
      <div class="citation-section-content">
        We acknowledge ACTRIS for providing the CLU (2019) dataset in this study, which was produced by the Finnish
        Meteorological Institute, and is available for download from <a href=""> https://cloudnet.fmi.fi/</a>.
        Measurements were supported by the European Space Agency through the FRM4RADAR project (ESA Contract No.
        4000122916/17/I-EF. The measurements at Norunda were also supported by ICOS Sweden.
      </div>
    </section>
    <section class="citation-section">
      <div class="summary-section-header">Data availability</div>
      <div class="citation-section-content">
        The ground-based remote-sensing data used in this article are generated by the European Research Infrastructure
        for the observation of Aerosol, Clouds and Trace Gases (ACTRIS) and are available from the ACTRIS Data Centre
        using the following link: <a href="#">https://hdl.handle.net/21.12132/1.cef4264f6fb24459</a>.
      </div>
    </section>
  </div>
</template>

<script lang="ts">
import { Component } from "vue-property-decorator";
import Vue from "vue";

@Component
export default class Citation extends Vue {
  smallCitation = true;

  toggleCitation() {
    this.smallCitation = !this.smallCitation;
  }

  get citationString() {
    let citeStr = `
        Some long citation string ... Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel leo pulvinar, efficitur mi at, pretium sem.
        Nulla ac quam eleifend, auctor velit sed, interdum erat. Sed porttitor posuere erat, et gravida nunc posuere
        vel. Aenean accumsan consectetur augue, non venenatis dui faucibus id. Suspendisse pellentesque sagittis
        vehicula. Sed quis nibh vel est eleifend lobortis eget quis ante. Cras faucibus mollis est quis interdum. Nullam
        ac metus sit amet augue lobortis maximus. Proin fermentum feugiat pharetra. Cras id justo lectus. Praesent sit
        amet dui ut neque aliquet rhoncus. Sed faucibus augue iaculis metus finibus fringilla. Sed arcu odio, pharetra
        non nibh vitae, euismod tincidunt nunc. Aenean vel laoreet erat. Sed varius tellus diam, vel consequat orci
        dictum nec. Mauris vel nunc nec dolor aliquet ornare in id nulla. Interdum et malesuada fames ac ante ipsum
        primis in faucibus. Aliquam dapibus viverra justo, eget molestie urna vehicula id. Etiam porta risus quis dolor
        condimentum suscipit. Aliquam bibendum sit amet diam vel gravida. Nam quam nisl, scelerisque at lorem vitae,
        commodo vulputate elit. Morbi lorem sapien, tempor quis fringilla at, sodales id augue. Nullam a nunc vel quam
        pretium rhoncus. Integer egestas ipsum at orci volutpat, et semper augue pretium. Vivamus egestas vulputate mi
        eu consequat. Donec facilisis gravida purus nec posuere. Donec et posuere turpis. Aliquam mattis elementum ipsum
        in fringilla. Maecenas faucibus dapibus orci non consequat. Nullam laoreet odio vitae eros euismod faucibus.
        Nunc non arcu arcu. Praesent nulla diam, malesuada vel vestibulum in, laoreet id orci. Donec semper ex viverra
        lobortis posuere. Curabitur faucibus tortor id ex ultricies malesuada. Vestibulum mauris justo, vestibulum vel
        est eget, feugiat sollicitudin lectus. Sed convallis purus mauris. Ut ac finibus turpis. Donec vestibulum mauris
        tortor, sit amet tincidunt mauris consectetur quis. Nulla sit amet iaculis ex. Ut eget libero iaculis, efficitur
        enim in, ultricies magna. Curabitur scelerisque lorem a laoreet dignissim. Aenean tempor eros auctor ante
        feugiat, lobortis scelerisque diam semper. Proin nisl metus, tincidunt ac accumsan faucibus, vestibulum id enim.
        Aliquam a rutrum nisl. Mauris eget mi sem. Donec dolor leo, sodales sit amet eros sed, vulputate aliquet nibh.
        Cras quis consequat ex. Fusce iaculis pellentesque velit, eget eleifend est tempus eu. Morbi vel ligula porta,
        mollis purus ut, vestibulum felis. Mauris luctus fringilla molestie. Cras in iaculis ante. Fusce eget nulla
        lectus. Sed luctus, lorem non rutrum euismod, diam libero mattis enim, non pretium augue lacus sed nisl. Fusce
        condimentum et dolor nec viverra. Mauris cursus lorem dolor, nec venenatis libero vestibulum at. Integer vitae
        metus nibh. Pellentesque ante nisl, interdum eget gravida et, lobortis quis elit. Curabitur pellentesque nunc
        sed purus ornare facilisis. Suspendisse sed ipsum a ex pharetra maximus sed vitae tellus. Nunc sagittis nulla
        purus, vitae maximus nunc ultricies eget. Pellentesque cursus purus sapien, at hendrerit urna scelerisque et.
        Suspendisse consequat lacus in est mollis, sit amet porttitor sem lobortis. Fusce hendrerit leo quis placerat
        tincidunt.
    `;
    citeStr = citeStr.trim().replace(/\s\s+/g, " ");
    return this.smallCitation ? citeStr.slice(0, 500) : citeStr.slice(0, 2000);
  }
}
</script>
