name: Production build
on: [push]
env:
  COMPOSE_FILE: .github/docker-compose.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        uses: docker/bake-action@v3
        with:
          workdir: .github
          targets: backend-prod,frontend-prod
          set: |
            *.cache-to=type=gha,mode=max
            *.cache-from=type=gha

      - name: Print logs
        if: always()
        run: docker-compose logs
