name: Lint and test
on: [push]
env:
  COMPOSE_FILE: .github/docker-compose.yml

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose build backend

      - name: Lint
        run: docker-compose run lint-backend

      - name: Run unit and integration tests
        run: docker-compose run test-backend

      - name: Run e2e tests
        run: docker-compose run e2e-test-backend

      - name: Print logs
        if: always()
        run: docker-compose logs

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose build frontend

      - name: Lint frontend
        run: docker-compose run lint-frontend

      - name: Run frontend unit tests
        run: docker-compose run test-frontend

      - name: Print logs
        if: always()
        run: docker-compose logs
